Fixing 2 new Serialization specifications errors
TensorProxy.cs(47,23): error UAC1001: Field 'data' is a candidate for serialization but Unity will skip it because its type 'Unity.InferenceEngine.Tensor' lacks [Serializable] attribute. To fix this, either: make the field private (if serialization is not desired), add [System.NonSerialized] (to explicitly mark it as non-serialized), or add [Serializable] to type 'Unity.InferenceEngine.Tensor' (if serialization is desired).

RigidBodySensorComponent.cs(36,32): error UAC1010: Field 'm_PoseExtractor' has [SerializeField] but its type 'Unity.MLAgents.Sensors.RigidBodyPoseExtractor' is not [Serializable]; Unity will ignore this field. Consider replacing [SerializeField] with [System.NonSerialized] or make the type [Serializable] if serialization is desired.